# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application
  
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]



jobs:
      
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        
  auth-to-ecr:
    permissions:
      id-token: write
      contents: read
      
    name: auth to ecr
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::788449246974:role/gha-ecr
        aws-region: us-east-1
        
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      
    - name: setup-pack
      uses: buildpacks/github-actions/setup-pack@v4.1.0

    - name: Build, Tag, and Push to ECR
      id: build-image
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: builder
        IMAGE_TAG: ${{ github.sha }}
      run: |
        #!/usr/bin/env bash
        set -euo pipefail
        pack build -p . --builder gcr.io/buildpacks/builder:v1 $REGISTRY/$REPOSITORY:$IMAGE_TAG --env "GOOGLE_ENTRYPOINT=gunicorn app:app"
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
        echo "::set-output name=image::$REGISTRY/$REPOSITORY:$IMAGE_TAG"
      shell: bash
      
    - name: Deploy to App Runner Image
      id: deploy-apprunner
      uses: awslabs/amazon-app-runner-deploy@main
      with:
          service: test-new-new
          image: ${{ steps.build-image.outputs.image }}
          access-role-arn: arn:aws:iam::788449246974:role/service-role/AppRunnerECRAccessRole
          region: us-east-1
          cpu : 1
          memory : 2
          port: 8080
          # Deprecated: wait-for-service-stability: true
          # The new way to control service stability timeout
          wait-for-service-stability-seconds: 1201

    - name: App Runner URL
      run: echo "App runner URL ${{ steps.deploy-apprunner.outputs.service-url }}" 
    
  
      
  
      
  
  
